// This file is generated by '/scripts/generate-types.ts'. Do not modify it manually.
// Instead, modify the schema in '/src/constants/app-config-schema.ts'
// and run 'yarn generate:types' to update this file.

export interface AppConfig {
  cliVersion: string;
  description?: string;
  embeds?: ({
    contentPageType: 'appManagement' | 'quickActions' | 'youtube' | 'youtubeVideo' | 'youtubeLive' | 'youtubeLiveUpcoming' | 'youtubeLiveNow' | 'youtubeLiveVod' | 'youtubeChatFrame' | 'twitch' | 'twitchEmbed';
    defaultStyles?: object;
    deviceType?: 'desktop' | 'mobile';
    isLoginRequired?: boolean;
    isResizable?: boolean;
    maxTruffleVersion?: string;
    minTruffleVersion?: string;
    resizeBounds?: {
      maxHeight: number;
      maxWidth: number;
      minHeight: number;
      minWidth: number;
    };
    slug: string;
    status?: 'published' | 'experimental' | 'disabled';
    tileProps?: {
      bgColor?: string;
      title?: string;
    };
    url: string;
    windowProps?: {
      initialDimensions?: {
        height: number;
        width: number;
      };
      title?: string;
      tooltipDescription?: string;
    };
  })[];
  name: string;
  path: string;
  products?: ({
    category?: string;
    name?: string;
    rank?: number;
    slug: string;
    variants: ({
      action?: {
        actions?: any;
        operation: 'webhook' | 'workflow' | 'exchange' | 'conditional' | 'apply-powerup';
        url?: any;
      };
      assets?: {
        path: string;
        quantity: number;
      }[];
      description?: string;
      name?: string;
      price: number;
      slug: string;
    })[];
  })[];
}