import { convertSchema } from 'joi-to-typescript';
import { APP_CONFIG_SCHEMA } from '../src/constants/app-config-schema';
import { writeFile } from 'fs/promises';

const WARNING = `// This file is generated by '/scripts/generate-types.ts'. Do not modify it manually.
// Instead, modify the schema in '/src/constants/app-config-schema.ts'
// and run 'yarn generate:types' to update this file.\n\n`;

const typeFileContent = convertSchema(
  {},
  APP_CONFIG_SCHEMA,
  'AppConfig',
)?.content;

if (typeFileContent)
  writeFile('src/types/generated.ts', WARNING + typeFileContent);
